remote-theme: hacker
title: Pause Random Superconductor Experiments: An Open Letter
description: We call on all labs and kitchens to immediately pause for at least 6 months the making of conductors with lower resistance than copper. 